name: Push Master

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: release-please-action
  rustdoc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache target
      uses: actions/cache@v3
      with:
        key: build
        path: |
          ./target

    - name: Re-generate rustdoc
      run: |
        rustup install nightly
        RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc
        rm -rf ./ci/doc
        mkdir ./ci/doc
        mv ./target/doc ./ci

    # `git add ./ci/doc/*` will return a non-zero exit code if the lock file is present.
    - name: Delete lock file
      run: rm ./ci/doc/.lock

    - name: Push updated docs
      run: |
        git config --global user.name github-actions[bot]
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git add ./ci/doc/*
        git commit -a -m "ci: Rustdoc."
        git push
