name: Pull Request

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  OLD_LCOV_FILE: lcov.info
  NEW_LCOV_FILE: new_lcov.info
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Audit
      run: |
        cargo install cargo-audit
        cargo audit

    - name: Format
      run: cargo fmt --check 

    - name: Build
      run: |
        rustup component add llvm-tools-preview
        export RUSTFLAGS="-Cinstrument-coverage"
        cargo build --verbose

    - name: Test
      run: LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose

    - name: Clippy
      run: cargo clippy --tests -- --deny warnings

    - name: Download grcov
      run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
    - name: Generate lcov
      continue-on-error: true
      run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o $NEW_LCOV_FILE 
    - name: Download lcov
      run: sudo apt install lcov
    - name: Compare coverage
      run: python3 coverage.py $GITHUB_HEAD_REF $GITHUB_BASE_REF $NEW_LCOV_FILE $OLD_LCOV_FILE

    - name: Benchmark
      run: python3 bench.py $GITHUB_HEAD_REF $GITHUB_BASE_REF
