name: Push Coverage

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ secrets.GH_TOKEN }}


jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: $GH_TOKEN

    - name: Calculate coverage
      env:
        LCOV_FILE: lcov.info
      run: |
        rustup component add llvm-tools-preview
        export RUSTFLAGS="-Cinstrument-coverage"
        cargo build --verbose
        LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
        rm $LCOV_FILE
        ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o $LCOV_FILE
    - name: Push updated coverage
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add lcov.info
        git commit -a -m "Updated code coverage"
        git push
