name: Push Coverage

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Re-generate coverage
      env:
        LCOV_FILE: lcov.info
        HTML_DIR: coverage
      run: |
        rustup component add llvm-tools-preview
        export RUSTFLAGS="-Cinstrument-coverage"
        cargo build --verbose
        LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
        rm $LCOV_FILE
        ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o $LCOV_FILE
    - name: Re-generate coverage html
      continue-on-error: true
      run: ./grcov . --binary-path ./target/debug/ -s . -t html --branch --ignore-not-existing --ignore "/*" -o $HTML_DIR
    - name: Push updated coverage
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add lcov.info
        git add coverage/*
        git commit -a -m "Updated code coverage"
        git push
