name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache target
      uses: actions/cache@v3
      with:
        key: build
        path: ./target
    
    - name: Add component
      run: rustup component add llvm-tools-preview
    
    - name: Format
      run: cargo fmt --check
      
    - name: Audit
      run: cargo audit
      
    - name: Build
      run: |
        export RUSTFLAGS="-Cinstrument-coverage"
        cargo build
      
    - name: Clippy
      run: cargo clippy --tests -- --deny warnings
      
    - name: Test
      run: |
        export LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test
        cargo test
      
    - name: Coverage - Download grcov
      run: wget -nc -q -O "grcov.tar.bz2" "https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2"
      # When the file is already downloaded it will exit with 1
      continue-on-error: true
      
    - name: Coverage - Extract grcov
      run: tar jxf grcov.tar.bz2
      
    - name: Coverage - Generate lcov
      run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
      
    - name: Codecov
      uses: codecov/codecov-action@v3
