name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache target
      uses: actions/cache@v3
      with:
        key: build
        path: ./target
    
    - name: Format
      run: cargo fmt --check
      
    - name: Audit
      run: cargo audit
      
    - name: Check
      run: cargo check
      
    - name: Clippy
      run: cargo clippy --tests -- --deny warnings
      
    - name: Test
      run: |
        rustup component add llvm-tools-preview
        env RUSTFLAGS="-C instrument-coverage" RUSTDOCFLAGS="-C instrument-coverage -Z unstable-options --persist-doctests ./target/debug/doctestbins" LLVM_PROFILE_FILE="coverage-%p-%m.profraw" cargo +nightly test

    - name: Coverage
      run: |
        cargo install grcov
        grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
      
    - name: Codecov
      uses: codecov/codecov-action@v3
